//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class kierowcy
    {
        public int idKierowcy { get; set; }
        public string nazwisko_prac { get; set; }
        public string imie_prac { get; set; }
        public int idKonta { get; set; }
        public string numer_tel_kierowcy { get; set; }
        public Nullable<sbyte> czy_aktywne { get; set; }
    
        public virtual konta konta { get; set; }

        public override string ToString()
        {
            return $"{idKierowcy}. {imie_prac} {nazwisko_prac}";
        }
    }
}
