//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klienci()
        {
            this.zamowienia = new HashSet<zamowienia>();
        }
    
        public int idKlienci { get; set; }
        public string nazwisko_klienta { get; set; }
        public string imie_klienta { get; set; }
        public string numer_tel_klienta { get; set; }
        public Nullable<sbyte> weryfikacja { get; set; }
        public int idKonta { get; set; }
        public sbyte czy_aktywne { get; set; }
    
        public virtual konta konta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamowienia> zamowienia { get; set; }
    }
}
