//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<administrator> administrator { get; set; }
        public DbSet<kierowcy> kierowcy { get; set; }
        public DbSet<klienci> klienci { get; set; }
        public DbSet<konta> konta { get; set; }
        public DbSet<pensja> pensja { get; set; }
        public DbSet<pojazdy> pojazdy { get; set; }
        public DbSet<szczegoly_zamowienia> szczegoly_zamowienia { get; set; }
        public DbSet<zamowienia> zamowienia { get; set; }
        public DbSet<model> model { get; set; }
    }
}
