//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_samochodu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public model_samochodu()
        {
            this.pojazdy = new HashSet<pojazdy>();
            this.zamowienia = new HashSet<zamowienia>();
        }
    
        public int idModel { get; set; }
        public string nazwa_model { get; set; }
        public Nullable<double> cena_za_km { get; set; }
        public string zdj_model { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pojazdy> pojazdy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamowienia> zamowienia { get; set; }
        public override string ToString()
        {
            return $"{idModel}. Nazwa: {nazwa_model}";
        }
    }
}
