//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrator> administrator { get; set; }
        public virtual DbSet<kierowcy> kierowcy { get; set; }
        public virtual DbSet<klienci> klienci { get; set; }
        public virtual DbSet<konta> konta { get; set; }
        public virtual DbSet<pensja> pensja { get; set; }
        public virtual DbSet<pojazdy> pojazdy { get; set; }
        public virtual DbSet<szczegoly_zamowienia> szczegoly_zamowienia { get; set; }
        public virtual DbSet<zamowienia> zamowienia { get; set; }
        public virtual DbSet<model_samochodu> model_samochodu { get; set; }
    }
}
