//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class pensja
    {
        public int idPensja { get; set; }
        public Nullable<double> stawka_godz { get; set; }
        public Nullable<System.DateTime> miesiac { get; set; }
        public int idKierowcy { get; set; }
        public override string ToString()
        {
            return $"{miesiac} ";
        }

    }
}
