//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class pojazdy
    {
        public int idPojazdy { get; set; }
        public string nr_rejestracji { get; set; }
        public Nullable<sbyte> dostepnosc { get; set; }
        public string status_pojazdu { get; set; }
        public int idModel { get; set; }
    
        public virtual model_samochodu model_samochodu { get; set; }
        public override string ToString()
        {
            return $"{idPojazdy}. Numer Rejestracji: {nr_rejestracji}";
        }
    }
}
