//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class szczegoly_zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public szczegoly_zamowienia()
        {
            this.zamowienia = new HashSet<zamowienia>();
        }
    
        public int idSzczegoly_zamowienia { get; set; }
        public string poczatek_panstwo { get; set; }
        public string poczatek_miasto { get; set; }
        public string poczatek_ulica { get; set; }
        public string poczatek_nr_domu { get; set; }
        public string poczatek_kod_pocztowy { get; set; }
        public string koniec_panstwo { get; set; }
        public string koniec_miasto { get; set; }
        public string koniec_ulica { get; set; }
        public string koniec_nr_domu { get; set; }
        public Nullable<double> ilosc_km { get; set; }
        public Nullable<double> cena { get; set; }
        public string koniec_kod_pocztowy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamowienia> zamowienia { get; set; }
    }
}
