//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma_Transportowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamowienia
    {
        public int idZamowienia { get; set; }
        public Nullable<System.DateTime> data_poczatku { get; set; }
        public Nullable<System.DateTime> data_konca { get; set; }
        public string status_zamowienia { get; set; }
        public int idKierowcy { get; set; }
        public int idPojazdy { get; set; }
        public int idKlienci { get; set; }
        public int idKonta { get; set; }
        public int idSzczegoly_zamowienia { get; set; }
        public int idAdministrator { get; set; }
        public Nullable<System.DateTime> data_zlozenia_zamowienia { get; set; }
        public Nullable<System.DateTime> zamowiona_data_realizacji { get; set; }
        public int idModel { get; set; }
        public string komentarz { get; set; }
        public Nullable<int> przewidywany_czas { get; set; }
    
        public virtual administrator administrator { get; set; }
        public virtual klienci klienci { get; set; }
        public virtual szczegoly_zamowienia szczegoly_zamowienia { get; set; }
        public virtual model_samochodu model_samochodu { get; set; }
        public override string ToString()
        {
            return $"ID Kierowcy: {idKierowcy} Data złożenia zamówienia: {data_zlozenia_zamowienia} Data początku: {data_poczatku} Data końca: {data_konca} Status: {status_zamowienia}";
        }
    }
}
